on: [push, pull_request]

jobs:
  gitlab_server_mirror:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Mirror and trigger CI job at https://gitlab.spack.io
      uses: stenongithub/gitlab-mirror-and-ci-action@0.2.8
      with:
        args: "https://gitlab.spack.io/ssg/superlu_dist.git"
      env:
        GITLAB_HOSTNAME: "gitlab.spack.io"
        GITLAB_USERNAME: "liuyang"
        GITLAB_PASSWORD: ${{ secrets.GITLAB_PASSWORD }}
        GITLAB_PROJECT_ID: "SSG/superlu_dist"
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        POLL_TIMEOUT: "800"